<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>735d10f0-ce4f-4d97-a405-ea6eb9d6f49d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.30" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="8.0.22" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartMillSync.Application\SmartMillSync.Application.csproj" />
    <ProjectReference Include="..\SmartMillSync.Infrastructure\SmartMillSync.Infrastructure.csproj" />
    <ProjectReference Include="..\SmartMillSync.Shared\SmartMillSync.Shared.csproj" />
  </ItemGroup>

</Project>
